---
- name: Check if Helm is already installed
  ansible.builtin.shell: helm version --short
  register: helm_installed
  ignore_errors: true
  changed_when: false

- name: Install Helm if it is not installed
  when: helm_installed.rc != 0
  block:
    - name: Download Helm installation script
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
        dest: /tmp/get-helm-3
        mode: "0755"
    - name: Run Helm installation script
      ansible.builtin.shell: /tmp/get-helm-3
    - name: Clean up Helm installation script
      ansible.builtin.file:
        path: /tmp/get-helm-3
        state: absent
