---
- name: Disable swap
  when: ansible_swaptotal_mb > 0
  ansible.builtin.command: swapoff -a

- name: Remove swap from /etc/fstab
  ansible.posix.mount:
    path: none
    fstype: swap
    state: absent
